language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
  - 7.3
  - 7.4
  - nightly

env:
    matrix:
        - COMPOSER_PARAM="update --no-progress --no-scripts --prefer-dist --optimize-autoloader --working-dir=. --prefer-source --prefer-lowest"
        - COMPOSER_PARAM="update --no-progress --no-scripts --prefer-dist --optimize-autoloader --working-dir=. --prefer-source"

before_script:
    - composer selfupdate
    - composer $COMPOSER_PARAM
    - composer install --no-scripts --no-progress
    - cp phpunit.xml.dist phpunit.xml

script:
  - php vendor/phpunit/phpunit/phpunit  --configuration ./phpunit.xml --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
  allow_failures:
    - php: nightly
    - php: 7.3
