name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Copy test suite config
      run: cp ./phpunit.xml.dist ./phpunit.xml 
      
    - name: Run Tests
      run: php bin/phpunit --coverage-text --coverage-clover ./test-clover.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_SECRET }}
        file: ./test-clover.xml
        flags: unittests
