name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Copy test suite config
      run: cp ./phpunit.xml.dist ./phpunit.xml 
      
    - name: Run Tests
      run: php bin/phpunit --coverage-text --coverage-clover ./test-clover.xml

    - uses: actions/upload-artifact@v2
      with:
        name: phpunit-result-clover
        path: ./phpunit-result-clover.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./phpunit-result-clover.xml
        flags: unittests
        name: clover-coverage
        fail_ci_if_error: false

    - name: Upload coverage to codeclimate
      uses: paambaati/codeclimate-action@v2.7.4
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        coverageLocations: |
          ./phpunit-result-clover.xml:clover
